### ISSUE TITLE
What are the fonts for?

### ISSUE THREAD

**Issue by moebiussurfing** [aiekick/ImCoolBar#2]
Hey, 
thanks for sharing @aiekick.
it looks pretty cool.

I get it [working in openFrameworks](https://github.com/moebiussurfing/ofxSurfingImGuiExtra/tree/master/0_NewExamples%20WIP/10_ImCoolBar), but I had to disable the fonts loading. 
(and it looks the same that your gifs)

What are they intended to do?

**Comment by aiekick** [comment]
Hello,

what font loading are you speaking ? what was the result with yout "font loading" ?

i dont understand the sense of your question. you are missing many details.. im not in your head :)

**Comment by moebiussurfing** [comment]
Sorry, I mean about this part: 
https://github.com/aiekick/ImCoolBar/blob/c9009a75b29feea43ff780947a05de55e25d8b8a/main.cpp#L205

I don't understand what it does... Maybe allows to use some font icons?
I just disabled, but I don't see any difference with your screencast/gif...

**Comment by aiekick** [comment]
This part can be removed for sure. 
Was used at first for using font icons (from CustomFont). 
but was not used at end. replaced by texture icons.
