### ISSUE TITLE
ImCoolBar is now available in Dear ImGui Bundle

### ISSUE THREAD

**Issue by pthom** [aiekick/ImCoolBar#4]
Hi @aiekick 

This is just for information (you can close this issue whenever you want).

ImCoolBar was added inside [Dear ImGui Bundle](https://github.com/pthom/imgui_bundle) (see [v1.0.0-beta1](https://github.com/pthom/imgui_bundle/releases/tag/v1.0.0-beta1))

You can see it in action in the [interactive emscripten demo](https://traineq.org/ImGuiBundle/emscripten/bin/demo_imgui_bundle.html): click on the "Widgets" tab.
<img width="346" alt="image" src="https://github.com/aiekick/ImCoolBar/assets/7694091/0e247f7e-317b-445a-883b-a36e6e44acbd">

It is thus also available in python within ImGui Bundle. See its [bindings "header"](https://github.com/pthom/imgui_bundle/blob/main/bindings/imgui_bundle/im_cool_bar.pyi).

* See [an example usage with python in ImGui Bundle](https://github.com/pthom/imgui_bundle/blob/bdbc70c3b9f437009ac3de959176f6b0b57589d8/bindings/imgui_bundle/demos_python/demo_widgets.py#L312-L345)
* See [the same example in C++](https://github.com/pthom/imgui_bundle/blob/bdbc70c3b9f437009ac3de959176f6b0b57589d8/bindings/imgui_bundle/demos_cpp/demo_widgets.cpp#L356-L399)

Cheers,

Pascal Thomet

**Comment by aiekick** [comment]
hello,

thats cool. thanks
